Basic imports and environment checks:
- PyTorch version verification is essential for reproducibility
- CUDA availability check - we'll need GPU access for future assignments
- If CUDA isn't available, try nvidia-smi in terminal to check GPU status

In [1]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.5.1+cu124
CUDA available: True


Converting Python list to tensor - torch.as_tensor() is preferred over torch.tensor()
as it can share memory with original data

In [10]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

tensor([1, 2, 3, 4, 5])


In [17]:
x = range(20)
x = torch.as_tensor(x)
y = []
for i, v in enumerate(x):
    if i % 3 == 0:
        y.append(v)
        
print(torch.stack(y, dim=0))

tensor([ 0,  3,  6,  9, 12, 15, 18])


In [18]:
x[0::3]

tensor([ 0,  3,  6,  9, 12, 15, 18])

Creating zero-filled tensor - useful for initializing buffers or placeholder tensors

In [3]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Creating tensor filled with ones - commonly used for masks or initialization

In [4]:
x = torch.ones(3, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating tensor with custom fill value - useful when you need specific constant values

In [5]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


Random tensor from normal distribution - key for weight initialization

In [23]:
x = torch.randn(3, 4, 3)
print(x)

tensor([[[-2.1910,  1.2700,  0.3905],
         [ 0.7628, -1.4595,  1.4810],
         [-0.9918,  1.8671,  0.3869],
         [-1.4160,  0.7261, -0.0239]],

        [[-1.4389, -1.2544, -0.1937],
         [ 0.2086, -2.3214,  0.2358],
         [ 0.5353, -1.1131,  0.5212],
         [ 2.0593, -0.5303,  0.5992]],

        [[ 0.3545, -0.4999, -0.6398],
         [ 0.6103,  0.4201, -1.2869],
         [ 0.4473,  0.8353,  0.7800],
         [-0.1892,  0.7829, -0.4899]]])


In [24]:
x.ndim

3

`zeros_like` creates tensor with same shape/dtype as input but filled with zeros

In [ ]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

`ones_like` - similar to before but fills with ones

In [ ]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

`full_like` - creates tensor matching input shape but with custom fill value

In [ ]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

`new_tensor` creates tensor with inherited properties (device/dtype) from source

In [ ]:
x = torch.zeros(3, 4, dtype=torch.bool)
y = x.new_tensor([1, 2, 3, 4])
print(y)

Broadcasting example with 2D tensors - shows automatic size matching

In [ ]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(z, z.shape)

Complex broadcasting with 5D tensors - demonstrates multi-dimension expansion

In [ ]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

Mean reduction - shows global and dimensional mean calculations

In [ ]:
x = torch.ones(3, 4, 5)
print(x.mean())
print(x.mean(-1))

Sum reduction - demonstrates summing across specified dimensions

In [ ]:
x = torch.ones(3, 4, 5)
print(x.sum(dim=0))
print(x.sum(dim=(1, 2)))

`keepdim`` usage - shows difference in output shapes

In [ ]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

Type conversion example - converting float tensor to long (int64)

In [ ]:
x = torch.randn(5, 5)
print(x.to(torch.long))

Reshaping with view - maintains underlying data pointer

In [ ]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(-1, 2)
print(y, y.shape)
print(z, z.shape)

Permute operation - reorders dimensions of tensor

In [ ]:
x = torch.randn(2, 3, 2)
y = x.permute(1, 2, 0)
print(y, y.shape)

Concatenation along specified dimension

In [ ]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

Stack operation - adds new dimension for combining tensors

In [ ]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

Performance comparison: Python list operations vs PyTorch operations

In [ ]:
import time


def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

PyTorch vectorized operation - significantly faster

In [ ]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

Type conversion examples - showing different conversion methods

In [ ]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

`arange` examples - different ways to create sequences

In [ ]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

In [28]:
print(x)

tensor([[[ 0.2396,  1.0896, -0.1992],
         [-1.5749,  0.2217, -0.8958],
         [ 0.5465, -0.0698, -0.0685],
         [ 0.7298,  0.4961, -0.3993]],

        [[ 1.5136,  0.7413, -1.5131],
         [-0.1696,  2.0988,  1.3328],
         [ 0.2153,  0.7144, -0.5948],
         [-0.3043, -1.4424,  0.4823]],

        [[-0.4183, -0.8408,  0.4138],
         [-0.5216,  0.9769, -1.1030],
         [-0.2563,  0.4654,  0.4270],
         [ 0.0707,  2.4274,  0.2111]]])


In [25]:
x = torch.randn(3, 4, 3)
n, m, _ = x.shape
y = torch.zeros(n, m)
for i in range(n):
    for j in range(m):
        maxval = float("-inf")
        for v in x[i, j]:
            if v > maxval:
                maxval = v
        y[i, j] = maxval
print(y)

tensor([[1.0896, 0.2217, 0.5465, 0.7298],
        [1.5136, 2.0988, 0.7144, 0.4823],
        [0.4138, 0.9769, 0.4654, 2.4274]])


In [65]:
x=torch.randn(3, 4)
a = 0
b = 0
for i in x.flatten():
    a += i
    b += 1
mean = a / b
c = 0
for i in x.flatten():
    if i > mean:
        c += 1
print(torch.as_tensor(c))


tensor(7)


In [66]:
x.ndim

2

In [69]:
y = []
for i in range(min(x.shape[0], x.shape[1])):
    y.append(x[i, x.shape[1] - i - 1])
torch.as_tensor(y)

tensor([-0.1672,  0.4994,  2.7196])

In [95]:
x = torch.randn(10)

In [96]:
x

tensor([-0.7961, -0.3833, -1.7750, -1.8434,  1.2864,  0.5855,  1.0285,  1.3601,
         0.1545, -1.5512])

In [97]:
if len(x) == 0:
    torch.as_tensor(x)
y = [x[0]]
for i in range(1, len(x)):
    y.append(y[i - 1] + x[i])
torch.as_tensor(y)

tensor([-0.7961, -1.1794, -2.9545, -4.7978, -3.5115, -2.9260, -1.8975, -0.5374,
        -0.3829, -1.9340])

In [113]:
x[0:2][0][:2].sum()+x[0:1][0][:2].sum()

tensor(-2.6735)

In [101]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
for i in range(0, x.shape[0]):
    for j in range(0, x.shape[1]):
        y[i, j] = x[i, j]
        if i > 0:
            y[i, j] += y[i - 1, j]
        if j > 0:
            y[i, j] += y[i, j - 1]
        if i > 0 and j > 0:
            y[i, j] -= y[i - 1, j - 1]
y

tensor([[-0.2218, -1.3367, -1.7241, -2.9111],
        [ 0.6019, -0.8122, -1.7512, -2.8097],
        [ 1.3458, -0.4468, -0.1452, -1.2139]])

In [128]:
x.cumsum(0).cumsum(1)

tensor([[-0.2218, -1.3367, -1.7241, -2.9111],
        [ 0.6019, -0.8122, -1.7512, -2.8097],
        [ 1.3458, -0.4468, -0.1452, -1.2139]])

In [130]:
c = torch.tensor(.1)

In [131]:
x

tensor([[-0.2218, -1.1150, -0.3874, -1.1870],
        [ 0.8236, -0.2991, -0.5516,  0.1285],
        [ 0.7440, -0.3785,  1.2405, -0.0102]])

In [132]:
y = torch.zeros_like(x)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if x[i, j] < c:
            y[i, j] = 0.0
        else:
            y[i, j] = x[i, j]
y

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.8236, 0.0000, 0.0000, 0.1285],
        [0.7440, 0.0000, 1.2405, 0.0000]])

In [138]:
x

tensor([[-0.2218, -1.1150, -0.3874, -1.1870],
        [ 0.8236, -0.2991, -0.5516,  0.1285],
        [ 0.7440, -0.3785,  1.2405, -0.0102]])

In [137]:
row, col = [], []
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if x[i, j] < c:
            row.append(i)
            col.append(j)
torch.as_tensor([row, col])

tensor([[0, 0, 0, 0, 1, 1, 2, 2],
        [0, 1, 2, 3, 1, 2, 1, 3]])

In [146]:
m=torch.randint(0, 2, (3,4))==1

In [147]:
y = []
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if m[i, j]:
            y.append(x[i, j])
torch.as_tensor(y)

tensor([-0.2218, -1.1870,  0.8236, -0.5516,  0.7440, -0.3785,  1.2405])

In [148]:
x[m]

tensor([-0.2218, -1.1870,  0.8236, -0.5516,  0.7440, -0.3785,  1.2405])

In [149]:
x = torch.randn(10)
y = torch.randn(10)

In [150]:
xy = []
for xi in x:
    xy.append(xi)
for yi in y:
    xy.append(yi)

z = []
for xy1, xy2 in zip(xy[1:], xy[:-1]):
    z.append(xy1 - xy2)
torch.as_tensor(z)

tensor([-0.2270, -0.8019,  0.3847, -1.2141,  1.6784, -0.6043, -1.4306,  1.2498,
        -0.9699, -0.9782,  3.0032, -1.6413, -0.0584,  0.7134, -0.9048,  0.1824,
         0.4316, -0.7614,  2.0675])

In [154]:
torch.concatenate([x,y]).diff()

tensor([-0.2270, -0.8019,  0.3847, -1.2141,  1.6784, -0.6043, -1.4306,  1.2498,
        -0.9699, -0.9782,  3.0032, -1.6413, -0.0584,  0.7134, -0.9048,  0.1824,
         0.4316, -0.7614,  2.0675])